### PR TITLE
Apply black to comply with the code style

### PR DESCRIPTION
**Pull request by sakurai-youhei**
Relates https://github.com/elastic/eland/pull/552

**Issue**:

```console
C:\Users\YouheiSakurai\git\myeland>python -m black --version
python -m black, 23.3.0 (compiled: yes)
Python (CPython) 3.11.0

C:\Users\YouheiSakurai\git\myeland>python -m black --check --target-version=py38 bin\eland_import_hub_model
would reformat bin\eland_import_hub_model

Oh no! 💥 💔 💥
1 file would be reformatted.
```

**Solution**:
```
C:\Users\YouheiSakurai\git\myeland>python -m black --target-version=py38 bin\eland_import_hub_model
reformatted bin\eland_import_hub_model

All done! ✨ 🍰 ✨
1 file reformatted.
```

### CODE REVIEW

**Review by valeriy42 — CHANGES_REQUESTED** [review]
Thank you for noticing this. It seems that `eland_import_hub_model` is not linted by black automatically in the CI. Can you please update the `noxfile.py` line 25, replacing "bin/" with "bin/*" to enforce checking all files?

**Review by valeriy42 — COMMENTED** [review]
Thank you for noticing this. It seems that `eland_import_hub_model` is not linted by black automatically in the CI. Can you please update the `noxfile.py` line 25, replacing "bin/" with "bin/*" to enforce checking all files?

**Review by valeriy42 — APPROVED** [review]
LGTM. If you move eland_import_hub_model in a follow-up PR, please ensure it will be automatically tested in the noxfile. Thank you!

**Comment by valeriy42** [comment]
> @valeriy42 Unlike shell, bin/* doesn't seem to be extracted by nox. Should I put bin/eland_import_hub_model instead?

Interesting. It seems that the behavior on Mac and Linux is different.

**Comment by sakurai-youhei** [comment]
@valeriy42 Once merged, I will start working on the next PR and ensure the file to be moved will be covered by the noxfile accordingly. Thanks!

**Pull request merged**
