### PR TITLE
[ML] adding inference results tests for pytorch transformer models

### PR DESCRIPTION
**Pull request by benwtrent**
This commit adds many integration tests for
 - downloading PyTorch models
 - Processing them locally prepping for Elasticsearch uploading
 - Uploading and deploying to Elasticsearch
 - Confirming inference results on the models.

The tests cover all our current NLP tasks over only some of our supported models. 

The models chosen to test were chosen for the broadest coverage over our supported tokenization and model wrapped types.

### CODE REVIEW

**Comment by benwtrent** [comment]
arg, CI failed and I cannot see in the logs, I am guessing ES threw an error or crashed? @sethmlarson are the ES logs uploaded anywhere?

**Comment by benwtrent** [comment]
Jenkins test this please

**Comment by benwtrent** [comment]
@sethmlarson The other node types on the client jenkins seem to be `n1-standard` which has 3.27 gb of ram vs the 1 gb of ram. 

So, a larger node type seems good to me. Something closer to 4 gb of ram should work. (JVM settings on ES could remain the same).

**Review by sethmlarson — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
