### PR TITLE
Add pytest-coverage

### LINKED ISSUE #314: Add Code Coverage
We need to add code coverage to eland to see if the existing test suite covers all scenarios

Initial thoughts are using any of the below:

- By using `pytest-cov`
Ref: https://pytest-cov.readthedocs.io/en/latest/readme.html#usage

- By using `coverage`
Ref: https://coverage.readthedocs.io/en/v4.5.x/cmd.html

### PR DESCRIPTION
**Pull request by V1NAY8**
Closes #314 
Added pytest-coverage

@sethmlarson  Please Review it :)

### CODE REVIEW

**Comment by sethmlarson** [comment]
jenkins test this please

**Review by sethmlarson — APPROVED** [review]
LGTM!

**Comment by V1NAY8** [comment]
😄

**Comment by V1NAY8** [comment]
Builds are good :)

**Pull request merged**
