### PR TITLE
Fix colab link

### PR DESCRIPTION
**Pull request by leemthompo**
The Colab button doesn't work in readthedocs, so just using standard markdown link format.

### CODE REVIEW

**Comment by pquentin** [comment]
@leemthompo Since the "Open in Colab" image is so recognizable, I restored it using the Markdown image syntax + the link syntax. What do you think? https://eland--632.org.readthedocs.build/en/632/examples/demo_notebook.html

**Comment by leemthompo** [comment]
@pquentin Perfect LGTM! 🪄


Unrelated, but I found a weirdness where `latest` doesn't map to v8.11.x on site.

https://eland.readthedocs.io/en/v8.11.0/examples/demo_notebook.html

versus

https://eland.readthedocs.io/en/latest/examples/demo_notebook.html

**Comment by pquentin** [comment]
> Unrelated, but I found a weirdness where `latest` doesn't map to v8.11.x on site.

`latest` include the latest commits to main. Your notebook fix landed just after the 8.11.0 release, which is why it isn't there. Does that make sense?

**Comment by leemthompo** [comment]
@pquentin I can't approve my own PR 😄

**Review by pquentin — APPROVED** [review]

**Comment by pquentin** [comment]
Hmm indeed my approval was enough. Interesting. Sorry about the noise!

**Pull request merged**
