### PR TITLE
Release 8.12.0

### PR DESCRIPTION
**Pull request by pquentin**

### CODE REVIEW

**Comment by pquentin** [comment]
buildkite test this please

**Review by ezimuel — APPROVED** [review]
LGTM

**Review by demjened — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
I would like to include #642 in this release please.

It requires a new feature added in Elasticsearch 8.12, which I why I hadn't merged the PR previously. I should have done so when the 8.12 snapshot build was added to CI so sorry about that.

**Comment by pquentin** [comment]
> I would like to include #642 in this release please.

Thanks, done! There was a review comment about docs, we can always add them to 8.12.1.
 
> It requires a new feature added in Elasticsearch 8.12, which I why I hadn't merged the PR previously. I should have done so when the 8.12 snapshot build was added to CI so sorry about that.

It makes me wonder if we should start adopting release branches - it's more complicated but would be more in line with other projects.

**Comment by davidkyle** [comment]
Thanks for merging my PR @pquentin and thank you for the release 🥳

**Pull request merged**
