### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by V1NAY8**
Changes made are:
- Refactored `eland/tests/*` to `test_eland/*` and imports used in tests.
- Updated `noxfile.py`
- Added code snippets to `contributing.rst`
- All tests (Including tests, doctests) were run and successful

@sethmlarson Please review, Happy to make any changes required 😄

### CODE REVIEW

**Comment by V1NAY8** [comment]
@sethmlarson . Can you please review this and merge into master? because i was writing tets for `mode` and wanted to see code coverage, it was messy
[Example](https://clients-ci.elastic.co/job/elastic+eland+master/lastBuild/ELASTICSEARCH_VERSION=8.0.0-SNAPSHOT,PYTHON_VERSION=3.8,TEST_SUITE=xpack,label=linux/console) which even includes coverage for tests as well.
- I have also added the `term-missing` paramter just to see at what lines the coverage is missing.

**Review by sethmlarson — CHANGES_REQUESTED** [review]
Instead of `test_eland/` let's do `tests/...`, also leave all the folder structure under `tests/` the same (ie don't rename `tests/dataframe` to `tests/test_dataframe`)

**Comment by V1NAY8** [comment]
Yep refactored them

**Comment by V1NAY8** [comment]
Right now builds are failing in master. The pytest issue looks similar to this https://stackoverflow.com/questions/10253826/path-issue-with-pytest-importerror-no-module-named-yadayadayada

So, made changes, 
this has to be merged before my other PR's

**Review by sethmlarson — APPROVED** [review]
LGTM! Will run CI to make sure everything is good.

**Comment by sethmlarson** [comment]
jenkins test this please

**Comment by V1NAY8** [comment]
Seth, can you re-ask jenkins to test this please. I made a small path mistake.

**Comment by sethmlarson** [comment]
jenkins test this please

**Comment by V1NAY8** [comment]
Not sure why it failed for 7.6,7.7. Looks like ES issue.

**Comment by sethmlarson** [comment]
It's an unrelated failure due to Elasticsearch changing the routes for ML trained models. I'll fix the issue.

**Comment by sethmlarson** [comment]
It looks like there's a merge conflict after I merged the progress bar PR, could you fix that up?

**Comment by V1NAY8** [comment]
Yes on it

**Comment by sethmlarson** [comment]
jenkins test this please

**Comment by V1NAY8** [comment]
Good bye merge conflicts :) Done!

**Comment by V1NAY8** [comment]
Finally, this looks good

**Review by sethmlarson — APPROVED** [review]
LGTM

**Pull request merged**
