### PR TITLE
Improve `es_info()` output readability

### LINKED ISSUE #239: Improve **es_info** method output readability
In my case, `es_info` method output readability is not optimal:
- tabulation breaks if screen width is too small (screenshot below)
- since `es_info` is probably only useful in interactive environment, it might be relevant to directly print output instead of returning a string

Capture d’écran 2020-07-16 à 20 10 23

### PR DESCRIPTION
**Pull request by V1NAY8**
Closes #239 
@sethmlarson 
I tried a formatting for `es_info()` output readability.
Apologies, if it's is not good.
Now we get formatted output both in both jupyter notebook and console.

One small issue:
Right now, I am not returning str from `es_info()` method.
One test case is failing in 
tests/etl/test_pandas_to_eland.py 
```python
assert "es_index_pattern : test-index" in df.es_info()
```
Please give me a suggestion, Happy to implement! 😄

### CODE REVIEW

**Comment by V1NAY8** [comment]
Here's an example for this:
```python
df = ed.DataFrame('localhost', 'flights')
df['Carrier'].value_counts()
df = df[(df.OriginAirportID == 'AMS') & (df.FlightDelayMin > 60)]
print(df.es_info())

```
```
==============================================ES_INFO===============================================

es_index_pattern : flights

===============================================INDEX================================================

es_index_field : _id

==============================================MAPPINGS==============================================

AvgTicketPrice:
    es_field_name:  AvgTicketPrice
    is_source:  True
    es_dtype:  float
    es_date_format:  None
    pd_dtype:  float64
    is_searchable:  True
    is_aggregatable:  True
    is_scripted:  False
    aggregatable_es_field_name:  AvgTicketPrice

Cancelled:
    es_field_name:  Cancelled
    is_source:  True
    es_dtype:  boolean
    es_date_format:  None
    pd_dtype:  bool
    is_searchable:  True
    is_aggregatable:  True
    is_scripted:  False
    aggregatable_es_field_name:  Cancelled
...

=============================================OPERATIONS=============================================

tasks : [('boolean_filter': ('boolean_filter': {'bool': {'must': [{'term': {'OriginAirportID': 'AMS'}}, {'range': {'FlightDelayMin': {'gt': 60}}}]}}))]

_source : ['AvgTicketPrice', 'Cancelled', 'Carrier', 'Dest', 'DestAirportID', 'DestCityName', 'DestCountry', 'DestLocation', 'DestRegion', 'DestWeather', 'DistanceKilometers', 'DistanceMiles', 'FlightDelay', 'FlightDelayMin', 'FlightDelayType', 'FlightNum', 'FlightTimeHour', 'FlightTimeMin', 'Origin', 'OriginAirportID', 'OriginCityName', 'OriginCountry', 'OriginLocation', 'OriginRegion', 'OriginWeather', 'dayOfWeek', 'timestamp']

body : {'query': {'bool': {'must': [{'term': {'OriginAirportID': 'AMS'}}, {'range': {'FlightDelayMin': {'gt': 60}}}]}}}

post_processing : []

None
```

**Comment by sethmlarson** [comment]
Just so you know the status of this PR, I actually have no idea what we *really* want from `es_info()`, so I might need to do some playing around with things locally before I decide the actual direction here :)

**Comment by sethmlarson** [comment]
I'm thinking just because I have no idea what we really want for this we should maybe close this PR for now. What do you think @V1NAY8?

**Comment by V1NAY8** [comment]
Yeah cool , closing this.

**Pull request closed without merging**
