### PR TITLE
Deal with the mad aggregation being removed in Pandas 2

### PR DESCRIPTION
**Pull request by bartbroere**
Pandas 2 has removed the `mad` aggregation. To be able to test whether eland's version produces the correct result, we can implement it ourselves, just for the tests.

Of course I'm open to other ideas (skipping the metric if we are in Pandas 2 perhaps?).

Related pandas issue: https://github.com/pandas-dev/pandas/issues/11787
Related to #601

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

**Review by pquentin — CHANGES_REQUESTED** [review]
Can you please run `nox -s format`?

**Comment by bartbroere** [comment]
> Can you please run `nox -s format`?

Done! Sorry about that.

**Comment by davidkyle** [comment]
@pquentin the PR build seems to have hung how can I restart it?

**Comment by pquentin** [comment]
buildkite test this please

**Pull request merged**
