### PR TITLE
Allow running demo_notebook in Google Colab

### PR DESCRIPTION
**Pull request by pquentin**
Adding an "Open in Colab" button was easy, but making the actual notebook runnable in Colab took way more effort. Ive followed the conventions used in https://github.com/elastic/elasticsearch-labs but:

 * I've used a hack to allow loading the test data from that notebook.
 * Making this nicer (including using the cloud id instead of host/port) will require changes in the tests.

I was not sure who to ask for review, feel free to change the reviewers list.

### CODE REVIEW

**Comment by pquentin** [comment]
Deleted Jenkins webhooks manually again, closing/reopening.

**Review by joshdevins — CHANGES_REQUESTED** [review]
+1 to making it run in Colab.

I don't love cloning the repo to get access to tests. I think it might be cleaner to move the functionality we need out of the test and into some "data loader" module. This way we just install eland and the module is there. To get access to the data, we could just download it from the GitHub blob url.

**Comment by pquentin** [comment]
@joshdevins What are your thoughts on this new approach? I've tested that `nox -s docs` works when ES is active, and that the notebook can be fully run in Colab too. Fetching the data from GitHub does seem like a nice approach, we're talking about less than 2MB here.

**Comment by pquentin** [comment]
I've also enabled the Read the Docs PR builds, so you can see:

 * the new API: https://eland--604.org.readthedocs.build/en/604/reference/io.html
 * the full notebook: https://eland--604.org.readthedocs.build/en/604/examples/demo_notebook.html

**Review by joshdevins — APPROVED** [review]

**Comment by pquentin** [comment]
Not going to merge this as is as I realized that `eland.etl` exposes various functions doing the same thing as mine.

**Comment by pquentin** [comment]
Closing in favor of #630.

**Pull request closed without merging**
