### PR TITLE
Make it easier to find an entrypoint on Windows

### LINKED ISSUE #551: A bit hard to find and run eland_import_hub_model on Windows
Right after `pip install eland`, neither `python -m eland` nor `eland_import-hub-model` works on Windows.

```shell
C:\Users\YouheiSakurai>python -m eland
C:\Program Files\Python311\python.exe: No module named eland.__main__; 'eland' is a package and cannot be directly executed

C:\Users\YouheiSakurai>eland_import_hub_model
'eland_import_hub_model' is not recognized as an internal or external command,
operable program or batch file.
```

1. `python -m eland` doesn't work because no of `eland.__main__`.
2. `eland_import-hub-model` doesn't work because [scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) is used instead of [console_scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) in `setup.py`.

image

As the above picture shows, `eland_import_hub_model` is not executable on Windows due to no file extension like `.exe`.

I will open a PR to solve this hassle on Windows.

### PR DESCRIPTION
**Pull request by sakurai-youhei**
Fixes #551.

- Make `python -m eland` available on all platforms.
- Make `eland_import_hub_model` executable on Windows.

**On Windows**:
```console
C:\Users\YouheiSakurai\git\myeland>python -m eland --help
usage: __main__.py [-h] (--url URL | --cloud-id CLOUD_ID) --hub-model-id HUB_MODEL_ID [--es-model-id ES_MODEL_ID]
                   [-u ES_USERNAME] [-p ES_PASSWORD] [--es-api-key ES_API_KEY]
...


C:\Users\YouheiSakurai\git\myeland>eland_import_hub_model --help
usage: eland_import_hub_model [-h] (--url URL | --cloud-id CLOUD_ID) --hub-model-id HUB_MODEL_ID
                              [--es-model-id ES_MODEL_ID] [-u ES_USERNAME] [-p ES_PASSWORD] [--es-api-key ES_API_KEY]
...

C:\Users\YouheiSakurai\git\myeland>where eland_import_hub_model
C:\Users\YouheiSakurai\AppData\Roaming\Python\Python311\Scripts\eland_import_hub_model.exe
```

**On Linux**
```console
root@3907c10cff9f:/# python -m eland --help
usage: __main__.py [-h] (--url URL | --cloud-id CLOUD_ID) --hub-model-id HUB_MODEL_ID [--es-model-id ES_MODEL_ID]
...

root@3907c10cff9f:/# eland_import_hub_model --help
usage: eland_import_hub_model [-h] (--url URL | --cloud-id CLOUD_ID) --hub-model-id HUB_MODEL_ID
...

root@3907c10cff9f:/# which eland_import_hub_model
/usr/local/bin/eland_import_hub_model

root@3907c10cff9f:/# file /usr/local/bin/eland_import_hub_model
/usr/local/bin/eland_import_hub_model: Python script, ASCII text executable
```

### CODE REVIEW

**Comment by sakurai-youhei** [comment]
I also touched codes for the following purposes:
- Overall code style compliance with the Black in the `eland_import_hub_model` script.
- Fix of mypy error `Unused "type: ignore" comment  [unused-ignore]` at `eland/ml/pytorch/transformers.py`.
- Fix of `ModuleNotFoundError: No module named 'torch'` where the torch isn't installed.

**Comment by joshdevins** [comment]
This looks fine to me. There's a lot of linting changes which I will just assume are correct but it would be good to have some verification from another reviewer more familiar with our Python styleguide. Do we also have someone/somewhere that we can verify the change on Windows?

**Comment by pquentin** [comment]
Thanks for fixing the lint/mypy issues! However, would you mind fixing them in a different pull request, to make this one easier to review. Also please avoid manual adjustments if they're not necessary to fix CI. It looks like those fixes are already splitted in commits, so this should not be too much effort. (But I can do it if you want)

**Comment by sakurai-youhei** [comment]
@joshdevins I should've separated the issues. I will attempt to describe and fix them one by one.

@pquentin Noted. I will open an issue/PR one by one these days.

I'm closing this PR as I put too many into one. Thank you for your comments, I appreciate them!

**Pull request closed without merging**
