### PR TITLE
[686] Replace check for Elasticsearch to str/list in ensure_es_client function

### PR DESCRIPTION
**Pull request by AshokChoudhary11**

### CODE REVIEW

**Comment by AshokChoudhary11** [comment]
Closes https://github.com/elastic/eland/issues/686

**Comment by pquentin** [comment]
Hello! Thanks for your contribution. Can you please sign the CLA?

**Comment by AshokChoudhary11** [comment]
Done

**Comment by pquentin** [comment]
buildkite test this please

**Review by pquentin — APPROVED** [review]
Thanks! Looks good to me.

**Pull request merged**
