### PR TITLE
Remove deprecated check_less_precise

### PR DESCRIPTION
**Pull request by bartbroere**
This removes the deprecated `check_less_precise` argument from one of the unit tests.

Part of the necessary adjustments to maybe start supporting `pandas>=2.0.0`

### CODE REVIEW

**Review by pquentin — CHANGES_REQUESTED** [review]
Do we also need to specify `check_exact=False`? According to the 2.0 docs, [rtol is defined as](https://pandas.pydata.org/pandas-docs/version/2.0/reference/api/pandas.testing.assert_series_equal.html):

> Relative tolerance. Only used when check_exact is False.

**Comment by bartbroere** [comment]
> Do we also need to specify `check_exact=False`? According to the 2.0 docs, [rtol is defined as](https://pandas.pydata.org/pandas-docs/version/2.0/reference/api/pandas.testing.assert_series_equal.html):
> 
> > Relative tolerance. Only used when check_exact is False.

Good catch! I'll update it.

**Comment by bartbroere** [comment]
> Do we also need to specify `check_exact=False`? According to the 2.0 docs, [rtol is defined as](https://pandas.pydata.org/pandas-docs/version/2.0/reference/api/pandas.testing.assert_series_equal.html):
> 
> > Relative tolerance. Only used when check_exact is False.



> > Do we also need to specify `check_exact=False`? According to the 2.0 docs, [rtol is defined as](https://pandas.pydata.org/pandas-docs/version/2.0/reference/api/pandas.testing.assert_series_equal.html):
> > > Relative tolerance. Only used when check_exact is False.
> 
> Good catch! I'll update it.

@pquentin I added the `check_exact=False` flag, but Github still doesn't think I "addressed the requested changes". Not sure how that works,  but I think it's all good now.

**Comment by pquentin** [comment]
buildkite test this please

**Pull request merged**
